config/routes.rb
NewsFlash::Application.routes.draw do
  resources :categories

  get "login" => "login#login"
  get "signup" => "login#signup"
	post "register" => "login#register"
	post "signin" => "login#signin"
	get "logout" => "login#logout"
	get "show-article" => "home#show"

  resources :articles
	resources :authors

  root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :author
	has_and_belongs_to_many :categories
	has_many :hits

	validates :title, presence: true
	validates :body, presence: true
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :articles

	validates :username, presence: true, uniqueness: true
	validates :first_name, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
end

app/models/hit.rb
class Hit < ActiveRecord::Base
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.where(:author_id => session[:author_id]).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

		if session[:author_id].nil?
			redirect_to login_path
		else
			@article.author_id = session[:author_id]

		  respond_to do |format|
		    if @article.save
		      format.html { redirect_to @article, notice: 'Article was successfully created.' }
		      format.json { render json: @article, status: :created, location: @article }
		    else
		      format.html { render action: "new" }
		      format.json { render json: @article.errors, status: :unprocessable_entity }
		    end
		  end
		end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@articles = Article.order("created_at DESC")
  end

	def show
		@article = Article.find(params[:id])

		save_hit params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
	end

	private
	def save_hit article_id
		@hit = Hit.new(:article_id => article_id, :author_id => 0)
		#author_id equals 0 means a hit from a guest
		@hit.author_id = session[:author_id] if session[:author_id]
		@hit.save
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end

	def signin
		@author = Author.find_by_username params[:username]
		if @author.nil?
			redirect_to login_path, :notice => "Username not found!"
		else
			session[:author_id] = @author.id
			redirect_to root_path
		end
	end

  def signup
		@author = Author.new
  end

	def register
		@author = Author.new(params[:author])

		if @author.save
			render :login
		else
			render :signup
		end
	end

	def logout
		session[:author_id] = nil
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def loggedin_author?
		@loggedin_author = Author.find(session[:author_id]) if session[:author_id]
		not @loggedin_author.nil?
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def get_formatted_author_for article
		@author = Author.find(article.author_id) if article.author_id
		"by #{@author.first_name} #{@author.last_name}"	
	end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

	<p>
		Categories
		<% for category in Category.find(:all) %>
		<div>
		  <%= check_box_tag "article[category_ids][]", category.id, @article.categories.include?(category) %>
		  <%= category.name %>
		</div>
		<% end %>
	</p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article, :class => "small_button round" %> |
<%= link_to 'Back', articles_path, :class => "small_button round" %>

app/views/articles/index.html.erb
<h1>My Articles</h1>

<%= link_to 'Create New Article', new_article_path, :class => "button round" %>

<% @articles.each do |article| %>
	<div class="formatted_article round">
		<p id="date"><%= article.created_at.strftime("%A, %h %d %Y, %H:%M hs") %></p>
		<p id="title"><%= article.title %></p>
		<p><%= article.body %></p><br />
    <p id="actions"><%= link_to 'Show', article, :class => "small_button round"%> |
		<%= link_to 'Edit', edit_article_path(article), :class => "small_button round" %> |
    <%= link_to 'Delete', article, confirm: 'Are you sure?', method: :delete, :class => "small_button round" %></p>
	</div>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path, :class => "small_button round" %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b><br />
  <%= @article.title %>
</p>

<p>
  <b>Body:</b><br />
  <%= @article.body %>
</p>

<p>
  <b>Categories:</b>
  <% @article.categories.each do |c| %>
		'<%= c.name %>' 
	<% end %>
</p>
<br />

<%= link_to 'Edit', edit_article_path(@article), :class => "small_button round" %> |
<%= link_to 'Back', articles_path, :class => "small_button round" %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<% @articles.each do |article| %>
	<div class="formatted_article round">
		<p id="date"><%= article.created_at.strftime("%A, %h %d %Y, %H:%M hs") %></p>
		<p id="title"><%= article.title %></p>
		<p id="author"><%= get_formatted_author_for article %></p>
		<p><%= article.body[0..140] %>...</p><br />
		<p id="readmore"><%= link_to 'read more...', :controller => :home, :action => :show, :id => article.id %></p><br />
		<p id="categories">
			<% article.categories.each do |c| %>
				<%= c.name %> 
			<% end %>		
		</p>
	</div>
<% end %>

app/views/home/show.html.erb
<div class="formatted_article round">
	<p id="date"><%= @article.created_at.strftime("%A, %h %d %Y, %H:%M hs") %></p>
	<p id="title"><%= @article.title %></p>
	<p id="author"><%= get_formatted_author_for @article %></p>
	<p><%= @article.body %></p><br />
</div>

<%= link_to 'Back', root_path, :class => "small_button round" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsFlash</title>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->    
  <%= stylesheet_link_tag 'blueprint/screen', media: 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  media: 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container">
      <header>
        <%= link_to image_tag("logo.png", alt: "NewsFlash", class: "round"), root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>|
						<% if loggedin_author? %>
							<li><%= "Hello #{@loggedin_author.first_name} #{@loggedin_author.last_name}! "%>
							<%= link_to "(log out)", logout_path %></li>|
							<li><%= link_to "My Articles", articles_path %></li>
						<% else %>
							<li><%= link_to "Log in", login_path %> or
							<%= link_to "Sign up", signup_path %></li>
						<% end %>
          </ul>
        </nav>
      </header>
      <section class="round">
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/login/login.html.erb
<h1>Log In</h1>
<p>Please use your username to log in</p>

<div>
	<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "error_explanation" %>
	<% end %>
</div>

<%= form_tag "/signin" do %>
	<div class="field">
		<b>Username</b><br />
		<%= text_field_tag :username %>
	</div>
	<div class="actions">
		<%= submit_tag "Log In!" %>
	</div>
<% end %>

app/views/login/signup.html.erb
<h1>Register now!</h1>

  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @author, :url => { :action => "register" } do |f| %>
	<div class="field">
		<%= f.label :username %><br />
		<%= f.text_field :username %>
	</div>
	<div class="field">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name %>
	</div>
	<div class="actions">
		<%= f.submit "Sign Up!" %>
	</div>
<% end %>